import Head from 'next/head'
import CardBanner from '../Components/CardBanner'
import Login from '../Components/Login'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projeto Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CardBanner/>
      <Login/>

    </div>
  )
}
